version: "3"
services:
  website:
    image: nginx
    ports:
    - "8081:80"
  website2:
    image: nginx
    ports:
      - "8082:80"
    networks:
       polanco:
        ipv4_address: 192.168.92.21
networks:
  polanco:
    ipam:
      driver: default
      config: 
        - subnet: "192.168.92.0/24"